apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deploy
  labels:
    name: postgresql-app
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql-pod
      app: voting-app
  template:
    metadata:
      name: postgresql-pod
      labels:
        name: postgresql-pod
        app: voting-app
    spec:
      containers:
      - name: postrgesql-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
