apiVersion: v1
kind: Service
metadata:
  name: redis-deploy-service
  labels:
    app: voting-app
spec:
  selector:
    app: voting-app
    name: worker-app-pod
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP

