apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: voting-app
spec:
  selector:
    app: voting-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort

