apiVersion: v1
kind: Pod
metadata:
  name: nginix-test
  labels:
    application: nginix-app
    version: 1.0.0
    environment: test
spec:
  containers:
    - name: nginix-container
      image: srinivasesapalli/nginx-test:1.0.0
      ports:
        containerPort: 80
