apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app
  labels:
    app: replication-app
    version: 1.0.0
spec:
  template:
    metadata:
      name: redis
      namespace: default
      labels:
        app: "myapp"
    spec:
      containers:
      - name: myapp
        image: "redis123"
  replicas: 2
