AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template deploys a VPC.
Parameters:
  bucketName:
    Description: Please enter the name for this VPC
    Type: String
    Default: dummy-44
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref bucketName
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - 's3:GetObject'
          Effect: Allow
          Resource: !Join
          - ''
          - - 'arn:aws:s3:::'
            - !Ref S3Bucket
            - /*
          Principal: '*'

  cloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: S3Bucket.s3.amazonaws.com
          Id: mydummyS3Origin
        Enabled: 'true'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: mydummyS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200

